version: '3.8'
services:
  # Контейнер для Django приложения
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8001:8001"  # Прокидываем порт приложения
    volumes:
      - ./app:/app  # Монтируем текущий каталог в директорию контейнера /app
    env_file:
      - .env
    entrypoint: [ "/app/entrypoint.sh" ]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env 
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
