version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: test
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
